import { StrictMode } from 'react'
import { renderToString } from 'react-dom/server'
// React Router 7 ships StaticRouter from the core package, not react-router-dom/server.
import { StaticRouter } from 'react-router'
import App from './App'
import { buildHead, renderHeadHtml } from './data/head'
import { pageSeo, notFoundSeo, indexableRoutes } from './data/seo'
import { SITE_URL, SITE_NAME, SITE_NOINDEX, absoluteUrl } from './data/site'
import type { SeoProps } from './components/Seo'

export interface RenderedRoute {
  /** Site-relative path, e.g. "/brake-repair-brampton". */
  path: string
  /** Output file, relative to dist/. */
  file: string
  head: string
  html: string
}

/** Maps a route path to its Seo entry. */
function seoForPath(path: string): SeoProps {
  if (path === '/404') return notFoundSeo
  if (path === '/') return pageSeo['home']
  const slug = path.replace(/^\//, '')
  return pageSeo[slug] ?? notFoundSeo
}

/**
 * `/` becomes index.html and `/foo` becomes foo/index.html for clean URLs.
 *
 * The 404 is the exception: it is written only as 404.html, the file static
 * hosts serve with a real 404 status. Emitting 404/index.html as well would
 * publish `/404` as a crawlable URL that answers 200 — a soft 404 of exactly
 * the kind this build exists to remove.
 */
function outputFile(path: string): string {
  if (path === '/') return 'index.html'
  if (path === '/404') return '404.html'
  return `${path.replace(/^\//, '')}/index.html`
}

/**
 * React emits hoistable resources — notably the `<link rel="preload">` for an
 * image marked fetchPriority="high" — at the front of renderToString's output.
 * Left there they land inside <div id="root">, after the stylesheet, so the
 * preload for the LCP image is discovered late and does nothing useful.
 * Splitting them out lets the prerenderer put them in <head> where they belong.
 */
function splitHoistables(html: string): { hoisted: string; body: string } {
  const match = html.match(/^(?:\s*<link\b[^>]*>)+/i)
  if (!match) return { hoisted: '', body: html }
  return {
    // React writes these React-style; lowercase them so the markup validates.
    hoisted: match[0]
      .replace(/\bimageSrcSet=/g, 'imagesrcset=')
      .replace(/\bimageSizes=/g, 'imagesizes=')
      .replace(/\bfetchPriority=/g, 'fetchpriority=')
      .trim(),
    body: html.slice(match[0].length),
  }
}

export function renderRoute(path: string): RenderedRoute {
  const seo = seoForPath(path)
  const rendered = renderToString(
    <StrictMode>
      <StaticRouter location={path}>
        <App />
      </StaticRouter>
    </StrictMode>,
  )
  const { hoisted, body } = splitHoistables(rendered)
  const head = renderHeadHtml(buildHead(seo))

  return {
    path,
    file: outputFile(path),
    head: hoisted ? `${head}\n    ${hoisted}` : head,
    html: body,
  }
}

/** Every route the prerenderer emits, including the non-indexed 404. */
export function allRoutes(): string[] {
  return [...indexableRoutes.map((route) => route.path), '/404']
}

export function sitemapXml(lastmod: string): string {
  const urls = indexableRoutes
    .map(
      (route) => `  <url>
    <loc>${absoluteUrl(route.path)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority.toFixed(1)}</priority>
  </url>`,
    )
    .join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`
}

/**
 * Netlify / Cloudflare Pages redirect rules, generated so the canonical host
 * can never drift from SITE_URL. Hardcoding the domain in a checked-in
 * _redirects file means changing VITE_SITE_URL silently leaves the host
 * redirects pointing at the old domain.
 */
export function redirectsFile(): string {
  const url = new URL(SITE_URL)
  const host = url.host
  const apex = host.replace(/^www\./, '')
  const hosts = apex === host ? [apex] : [apex, `www.${apex}`]

  const canonical = hosts
    .flatMap((h) =>
      ['http', 'https']
        .map((scheme) =>
          `${scheme}://${h}` === SITE_URL
            ? null
            : `${scheme}://${h}/*  ${SITE_URL}/:splat  301!`,
        )
        .filter(Boolean),
    )
    .join('\n')

  return `# Generated by scripts/prerender.mjs from VITE_SITE_URL. Do not edit by hand.
# Order matters: the first match wins.

# Force the canonical host and scheme. Without this, every page is reachable at
# several URLs and search engines have to guess which one is authoritative.
${canonical}

# Retired page. Dent work is covered by the auto body repair page, which has a
# dedicated "Dent Repair" section — a 301 has to land on the closest equivalent
# content or Google treats it as a soft 404 and drops the old URL's signals.
# This is a real 301 rather than a client-side <Navigate>, which returns 200 and
# leaves the old URL in the index.
/dent-repair-brampton  /auto-body-repair-brampton  301!

# Every route is prerendered to its own HTML file, so there is deliberately no
# SPA rewrite here. Unmatched paths fall through to 404.html with a real 404
# status instead of being rewritten to index.html, which would return 200 for
# every bad URL and produce soft 404s across the whole site.
`
}

export function robotsTxt(): string {
  if (SITE_NOINDEX) {
    return `# ${SITE_NAME} — non-production deployment (${SITE_URL})
# Generated by scripts/prerender.mjs.
#
# This is a preview or branch deployment serving a copy of the production site.
# Crawling is disallowed so it cannot compete with production in the index.

User-agent: *
Disallow: /
`
  }

  return `# ${SITE_NAME} — ${SITE_URL}
# Generated by scripts/prerender.mjs. Edit src/entry-server.tsx to change.

User-agent: *
Allow: /

# No server-side search, faceting, or session parameters exist on this site,
# so nothing needs to be excluded from crawling.

Sitemap: ${SITE_URL}/sitemap.xml
`
}

export { SITE_URL }
