// AUTO-GENERATED by scripts/gen_photos.py - do not edit by hand.
// Real Sultan Motors photography, cropped and colour-corrected per slot.
import aboutTechnicianHandTool760 from '../assets/photos/about-technician-hand-tool-760.webp'
import aboutTechnicianHandTool1400 from '../assets/photos/about-technician-hand-tool-1400.webp'
import aboutShopWide1100 from '../assets/photos/about-shop-wide-1100.webp'
import aboutShopWide2000 from '../assets/photos/about-shop-wide-2000.webp'
import aboutShopFloorElevated760 from '../assets/photos/about-shop-floor-elevated-760.webp'
import aboutShopFloorElevated1400 from '../assets/photos/about-shop-floor-elevated-1400.webp'
import aboutTechnicianRoofPanel1280 from '../assets/photos/about-technician-roof-panel-1280.webp'
import aboutTechnicianRoofPanel2400 from '../assets/photos/about-technician-roof-panel-2400.webp'
import aboutMaskedPanelPrep760 from '../assets/photos/about-masked-panel-prep-760.webp'
import aboutMaskedPanelPrep1400 from '../assets/photos/about-masked-panel-prep-1400.webp'
import aboutStructuralRepair760 from '../assets/photos/about-structural-repair-760.webp'
import aboutStructuralRepair1400 from '../assets/photos/about-structural-repair-1400.webp'
import shopFloorCollisionBay1280 from '../assets/photos/shop-floor-collision-bay-1280.webp'
import shopFloorCollisionBay2400 from '../assets/photos/shop-floor-collision-bay-2400.webp'
import bodyFillerBumperRepair500 from '../assets/photos/body-filler-bumper-repair-500.webp'
import bodyFillerBumperRepair900 from '../assets/photos/body-filler-bumper-repair-900.webp'
import collisionFramePull500 from '../assets/photos/collision-frame-pull-500.webp'
import collisionFramePull900 from '../assets/photos/collision-frame-pull-900.webp'
import diagnosticsObdPortTile500 from '../assets/photos/diagnostics-obd-port-tile-500.webp'
import diagnosticsObdPortTile900 from '../assets/photos/diagnostics-obd-port-tile-900.webp'
import maintenanceOilServiceTile500 from '../assets/photos/maintenance-oil-service-tile-500.webp'
import maintenanceOilServiceTile900 from '../assets/photos/maintenance-oil-service-tile-900.webp'
import heavyMechanicalEngineOut500 from '../assets/photos/heavy-mechanical-engine-out-500.webp'
import heavyMechanicalEngineOut900 from '../assets/photos/heavy-mechanical-engine-out-900.webp'
import shopExteriorBrampton1280 from '../assets/photos/shop-exterior-brampton-1280.webp'
import shopExteriorBrampton2400 from '../assets/photos/shop-exterior-brampton-2400.webp'
import craftsmanshipPainterSpraying720 from '../assets/photos/craftsmanship-painter-spraying-720.webp'
import craftsmanshipPainterSpraying1280 from '../assets/photos/craftsmanship-painter-spraying-1280.webp'
import autobodyG1PanelPrep560 from '../assets/photos/autobody-g1-panel-prep-560.webp'
import autobodyG1PanelPrep1000 from '../assets/photos/autobody-g1-panel-prep-1000.webp'
import autobodyG2DoorSanded560 from '../assets/photos/autobody-g2-door-sanded-560.webp'
import autobodyG2DoorSanded1000 from '../assets/photos/autobody-g2-door-sanded-1000.webp'
import autobodyG3BlendPanel560 from '../assets/photos/autobody-g3-blend-panel-560.webp'
import autobodyG3BlendPanel1000 from '../assets/photos/autobody-g3-blend-panel-1000.webp'
import autobodyHeroPrimerCoupe1100 from '../assets/photos/autobody-hero-primer-coupe-1100.webp'
import autobodyHeroPrimerCoupe2000 from '../assets/photos/autobody-hero-primer-coupe-2000.webp'
import autobodyIntroPrimerDoor760 from '../assets/photos/autobody-intro-primer-door-760.webp'
import autobodyIntroPrimerDoor1400 from '../assets/photos/autobody-intro-primer-door-1400.webp'
import autobodyWhyGuideCoat760 from '../assets/photos/autobody-why-guide-coat-760.webp'
import autobodyWhyGuideCoat1400 from '../assets/photos/autobody-why-guide-coat-1400.webp'
import electricalG1Harness560 from '../assets/photos/electrical-g1-harness-560.webp'
import electricalG1Harness1000 from '../assets/photos/electrical-g1-harness-1000.webp'
import electricalG2WiringRepair560 from '../assets/photos/electrical-g2-wiring-repair-560.webp'
import electricalG2WiringRepair1000 from '../assets/photos/electrical-g2-wiring-repair-1000.webp'
import electricalG3BumperInternals560 from '../assets/photos/electrical-g3-bumper-internals-560.webp'
import electricalHeroFrontClip1100 from '../assets/photos/electrical-hero-front-clip-1100.webp'
import electricalHeroFrontClip2000 from '../assets/photos/electrical-hero-front-clip-2000.webp'
import electricalIntroConnector760 from '../assets/photos/electrical-intro-connector-760.webp'
import electricalIntroConnector1400 from '../assets/photos/electrical-intro-connector-1400.webp'
import electricalWhyDashHarness760 from '../assets/photos/electrical-why-dash-harness-760.webp'
import electricalWhyDashHarness1400 from '../assets/photos/electrical-why-dash-harness-1400.webp'
import autoRepairG1RepairBay560 from '../assets/photos/auto-repair-g1-repair-bay-560.webp'
import autoRepairG1RepairBay1000 from '../assets/photos/auto-repair-g1-repair-bay-1000.webp'
import autoRepairG2Diagnostics560 from '../assets/photos/auto-repair-g2-diagnostics-560.webp'
import autoRepairG2Diagnostics1000 from '../assets/photos/auto-repair-g2-diagnostics-1000.webp'
import autoRepairG3PowerTool560 from '../assets/photos/auto-repair-g3-power-tool-560.webp'
import autoRepairG3PowerTool1000 from '../assets/photos/auto-repair-g3-power-tool-1000.webp'
import autoRepairHeroShop1100 from '../assets/photos/auto-repair-hero-shop-1100.webp'
import autoRepairHeroShop2000 from '../assets/photos/auto-repair-hero-shop-2000.webp'
import autoRepairIntroBay760 from '../assets/photos/auto-repair-intro-bay-760.webp'
import autoRepairIntroBay1400 from '../assets/photos/auto-repair-intro-bay-1400.webp'
import autoRepairWhyHeavyMechanical760 from '../assets/photos/auto-repair-why-heavy-mechanical-760.webp'
import autoRepairWhyHeavyMechanical1400 from '../assets/photos/auto-repair-why-heavy-mechanical-1400.webp'
import brakeG1FrontTeardown560 from '../assets/photos/brake-g1-front-teardown-560.webp'
import brakeG1FrontTeardown1000 from '../assets/photos/brake-g1-front-teardown-1000.webp'
import brakeG2CaliperInspection560 from '../assets/photos/brake-g2-caliper-inspection-560.webp'
import brakeG2CaliperInspection1000 from '../assets/photos/brake-g2-caliper-inspection-1000.webp'
import brakeG3RotorsPadsLift560 from '../assets/photos/brake-g3-rotors-pads-lift-560.webp'
import brakeG3RotorsPadsLift1000 from '../assets/photos/brake-g3-rotors-pads-lift-1000.webp'
import brakeHeroWheelOffRotor1100 from '../assets/photos/brake-hero-wheel-off-rotor-1100.webp'
import brakeHeroWheelOffRotor2000 from '../assets/photos/brake-hero-wheel-off-rotor-2000.webp'
import brakeIntroRotorHub760 from '../assets/photos/brake-intro-rotor-hub-760.webp'
import brakeIntroRotorHub1400 from '../assets/photos/brake-intro-rotor-hub-1400.webp'
import brakeWhyRotorCaliper760 from '../assets/photos/brake-why-rotor-caliper-760.webp'
import brakeWhyRotorCaliper1400 from '../assets/photos/brake-why-rotor-caliper-1400.webp'
import diagnosticsG1ObdPort560 from '../assets/photos/diagnostics-g1-obd-port-560.webp'
import diagnosticsG1ObdPort1000 from '../assets/photos/diagnostics-g1-obd-port-1000.webp'
import diagnosticsG2FuseboxWiring560 from '../assets/photos/diagnostics-g2-fusebox-wiring-560.webp'
import diagnosticsG2FuseboxWiring1000 from '../assets/photos/diagnostics-g2-fusebox-wiring-1000.webp'
import diagnosticsG3TechTeamBay560 from '../assets/photos/diagnostics-g3-tech-team-bay-560.webp'
import diagnosticsHeroScanBay1100 from '../assets/photos/diagnostics-hero-scan-bay-1100.webp'
import diagnosticsHeroScanBay2000 from '../assets/photos/diagnostics-hero-scan-bay-2000.webp'
import diagnosticsIntroObdPlug760 from '../assets/photos/diagnostics-intro-obd-plug-760.webp'
import diagnosticsIntroObdPlug1400 from '../assets/photos/diagnostics-intro-obd-plug-1400.webp'
import diagnosticsWhyLiveData760 from '../assets/photos/diagnostics-why-live-data-760.webp'
import diagnosticsWhyLiveData1400 from '../assets/photos/diagnostics-why-live-data-1400.webp'
import maintenanceG1SparkPlug560 from '../assets/photos/maintenance-g1-spark-plug-560.webp'
import maintenanceG1SparkPlug1000 from '../assets/photos/maintenance-g1-spark-plug-1000.webp'
import maintenanceG2OilBottles560 from '../assets/photos/maintenance-g2-oil-bottles-560.webp'
import maintenanceG2OilBottles1000 from '../assets/photos/maintenance-g2-oil-bottles-1000.webp'
import maintenanceG3UnderbodyCheck560 from '../assets/photos/maintenance-g3-underbody-check-560.webp'
import maintenanceHeroOilDrain1100 from '../assets/photos/maintenance-hero-oil-drain-1100.webp'
import maintenanceHeroOilDrain2000 from '../assets/photos/maintenance-hero-oil-drain-2000.webp'
import maintenanceIntroOilJugs760 from '../assets/photos/maintenance-intro-oil-jugs-760.webp'
import maintenanceIntroOilJugs1400 from '../assets/photos/maintenance-intro-oil-jugs-1400.webp'
import maintenanceWhyOilService760 from '../assets/photos/maintenance-why-oil-service-760.webp'
import maintenanceWhyOilService1400 from '../assets/photos/maintenance-why-oil-service-1400.webp'
import paintG1MaskedRear560 from '../assets/photos/paint-g1-masked-rear-560.webp'
import paintG1MaskedRear1000 from '../assets/photos/paint-g1-masked-rear-1000.webp'
import paintG2MaskingDetail560 from '../assets/photos/paint-g2-masking-detail-560.webp'
import paintG2MaskingDetail1000 from '../assets/photos/paint-g2-masking-detail-1000.webp'
import paintG3FinishedGloss560 from '../assets/photos/paint-g3-finished-gloss-560.webp'
import paintG3FinishedGloss1000 from '../assets/photos/paint-g3-finished-gloss-1000.webp'
import paintHeroBoothSpray1100 from '../assets/photos/paint-hero-booth-spray-1100.webp'
import paintHeroBoothSpray2000 from '../assets/photos/paint-hero-booth-spray-2000.webp'
import paintIntroSpraying760 from '../assets/photos/paint-intro-spraying-760.webp'
import paintIntroSpraying1400 from '../assets/photos/paint-intro-spraying-1400.webp'
import paintWhyMaskedBooth760 from '../assets/photos/paint-why-masked-booth-760.webp'
import paintWhyMaskedBooth1400 from '../assets/photos/paint-why-masked-booth-1400.webp'
import collisionG1FrontDamage560 from '../assets/photos/collision-g1-front-damage-560.webp'
import collisionG1FrontDamage1000 from '../assets/photos/collision-g1-front-damage-1000.webp'
import collisionG2Sectioning560 from '../assets/photos/collision-g2-sectioning-560.webp'
import collisionG2Sectioning1000 from '../assets/photos/collision-g2-sectioning-1000.webp'
import collisionG3Restored560 from '../assets/photos/collision-g3-restored-560.webp'
import collisionG3Restored1000 from '../assets/photos/collision-g3-restored-1000.webp'
import collisionHeroFrameAnchor1100 from '../assets/photos/collision-hero-frame-anchor-1100.webp'
import collisionHeroFrameAnchor2000 from '../assets/photos/collision-hero-frame-anchor-2000.webp'
import collisionIntroTeardown760 from '../assets/photos/collision-intro-teardown-760.webp'
import collisionIntroTeardown1400 from '../assets/photos/collision-intro-teardown-1400.webp'
import collisionWhyStructural760 from '../assets/photos/collision-why-structural-760.webp'
import collisionWhyStructural1400 from '../assets/photos/collision-why-structural-1400.webp'
import engineG1RadiatorCondenser560 from '../assets/photos/engine-g1-radiator-condenser-560.webp'
import engineG1RadiatorCondenser1000 from '../assets/photos/engine-g1-radiator-condenser-1000.webp'
import engineG2FrontClipApart560 from '../assets/photos/engine-g2-front-clip-apart-560.webp'
import engineG2FrontClipApart1000 from '../assets/photos/engine-g2-front-clip-apart-1000.webp'
import engineG3BayHoodUp560 from '../assets/photos/engine-g3-bay-hood-up-560.webp'
import engineG3BayHoodUp1000 from '../assets/photos/engine-g3-bay-hood-up-1000.webp'
import engineHeroHoodUpLift1100 from '../assets/photos/engine-hero-hood-up-lift-1100.webp'
import engineHeroHoodUpLift2000 from '../assets/photos/engine-hero-hood-up-lift-2000.webp'
import engineIntroBayOpen760 from '../assets/photos/engine-intro-bay-open-760.webp'
import engineIntroBayOpen1400 from '../assets/photos/engine-intro-bay-open-1400.webp'
import engineWhyRemovedEngine760 from '../assets/photos/engine-why-removed-engine-760.webp'
import engineWhyRemovedEngine1400 from '../assets/photos/engine-why-removed-engine-1400.webp'
import safetyHeroVehicleOnHoist1100 from '../assets/photos/safety-hero-vehicle-on-hoist-1100.webp'
import safetyHeroVehicleOnHoist2000 from '../assets/photos/safety-hero-vehicle-on-hoist-2000.webp'
import safetyIntroJettaInspection760 from '../assets/photos/safety-intro-jetta-inspection-760.webp'
import safetyIntroJettaInspection1400 from '../assets/photos/safety-intro-jetta-inspection-1400.webp'
import safetyWhyInspectionLift760 from '../assets/photos/safety-why-inspection-lift-760.webp'
import safetyWhyInspectionLift1400 from '../assets/photos/safety-why-inspection-lift-1400.webp'
import suspensionG1CoilMacro560 from '../assets/photos/suspension-g1-coil-macro-560.webp'
import suspensionG1CoilMacro1000 from '../assets/photos/suspension-g1-coil-macro-1000.webp'
import suspensionG2StrutDetail560 from '../assets/photos/suspension-g2-strut-detail-560.webp'
import suspensionG2StrutDetail1000 from '../assets/photos/suspension-g2-strut-detail-1000.webp'
import suspensionG3Underbody560 from '../assets/photos/suspension-g3-underbody-560.webp'
import suspensionHeroStrutArm1100 from '../assets/photos/suspension-hero-strut-arm-1100.webp'
import suspensionHeroStrutArm2000 from '../assets/photos/suspension-hero-strut-arm-2000.webp'
import suspensionIntroHoistCorner760 from '../assets/photos/suspension-intro-hoist-corner-760.webp'
import suspensionIntroHoistCorner1400 from '../assets/photos/suspension-intro-hoist-corner-1400.webp'
import suspensionWhyStrutCoil760 from '../assets/photos/suspension-why-strut-coil-760.webp'
import suspensionWhyStrutCoil1400 from '../assets/photos/suspension-why-strut-coil-1400.webp'
import transmissionG1Underbody560 from '../assets/photos/transmission-g1-underbody-560.webp'
import transmissionG2SubframeDriveline560 from '../assets/photos/transmission-g2-subframe-driveline-560.webp'
import transmissionG2SubframeDriveline1000 from '../assets/photos/transmission-g2-subframe-driveline-1000.webp'
import transmissionG3UnderbodyTech560 from '../assets/photos/transmission-g3-underbody-tech-560.webp'
import transmissionHeroFrameDriveline1100 from '../assets/photos/transmission-hero-frame-driveline-1100.webp'
import transmissionHeroFrameDriveline2000 from '../assets/photos/transmission-hero-frame-driveline-2000.webp'
import transmissionIntroUnitJack760 from '../assets/photos/transmission-intro-unit-jack-760.webp'
import transmissionIntroUnitJack1400 from '../assets/photos/transmission-intro-unit-jack-1400.webp'
import transmissionWhyDriveline760 from '../assets/photos/transmission-why-driveline-760.webp'
import transmissionWhyDriveline1400 from '../assets/photos/transmission-why-driveline-1400.webp'

export interface Photo {
  src: string
  srcSet: string
  width: number
  height: number
  sources: { w: number; url: string }[]
  alt: string
}

export const photos: Record<string, Photo> = {
  'about.cert': {
    src: aboutTechnicianHandTool1400,
    srcSet: `${aboutTechnicianHandTool760} 760w, ${aboutTechnicianHandTool1400} 1400w`,
    width: 1400,
    height: 667,
    sources: [{ w: 760, url: aboutTechnicianHandTool760 }, { w: 1400, url: aboutTechnicianHandTool1400 }],
    alt: "Sultan Motors technician working a replacement roof panel with a hand tool inside the Brampton workshop",
  },
  'about.hero': {
    src: aboutShopWide2000,
    srcSet: `${aboutShopWide1100} 1100w, ${aboutShopWide2000} 2000w`,
    width: 2000,
    height: 909,
    sources: [{ w: 1100, url: aboutShopWide1100 }, { w: 2000, url: aboutShopWide2000 }],
    alt: "Wide view of the Sultan Motors collision repair bay in Brampton with vehicles on hoists and technicians at work",
  },
  'about.story': {
    src: aboutShopFloorElevated1400,
    srcSet: `${aboutShopFloorElevated760} 760w, ${aboutShopFloorElevated1400} 1400w`,
    width: 1400,
    height: 787,
    sources: [{ w: 760, url: aboutShopFloorElevated760 }, { w: 1400, url: aboutShopFloorElevated1400 }],
    alt: "Elevated view across the Sultan Motors shop floor showing vehicles on hoists and a car masked for paint",
  },
  'about.team': {
    src: aboutTechnicianRoofPanel2400,
    srcSet: `${aboutTechnicianRoofPanel1280} 1280w, ${aboutTechnicianRoofPanel2400} 2400w`,
    width: 2400,
    height: 1048,
    sources: [{ w: 1280, url: aboutTechnicianRoofPanel1280 }, { w: 2400, url: aboutTechnicianRoofPanel2400 }],
    alt: "Sultan Motors technician inspecting a new roof panel assembly beneath the shop's branded signage",
  },
  'about.value1': {
    src: aboutMaskedPanelPrep1400,
    srcSet: `${aboutMaskedPanelPrep760} 760w, ${aboutMaskedPanelPrep1400} 1400w`,
    width: 1400,
    height: 933,
    sources: [{ w: 760, url: aboutMaskedPanelPrep760 }, { w: 1400, url: aboutMaskedPanelPrep1400 }],
    alt: "Rear quarter panel masked with tape and skimmed with body filler during a precision panel repair at Sultan Motors",
  },
  'about.value2': {
    src: aboutStructuralRepair1400,
    srcSet: `${aboutStructuralRepair760} 760w, ${aboutStructuralRepair1400} 1400w`,
    width: 1400,
    height: 933,
    sources: [{ w: 760, url: aboutStructuralRepair760 }, { w: 1400, url: aboutStructuralRepair1400 }],
    alt: "Front clip cut away from a unibody on the hoist during structural collision repair at Sultan Motors",
  },
  'home.story': {
    src: shopFloorCollisionBay2400,
    srcSet: `${shopFloorCollisionBay1280} 1280w, ${shopFloorCollisionBay2400} 2400w`,
    width: 2400,
    height: 1165,
    sources: [{ w: 1280, url: shopFloorCollisionBay1280 }, { w: 2400, url: shopFloorCollisionBay2400 }],
    alt: "Sultan Motors collision repair bay in Brampton with vehicles on two-post hoists and technicians refinishing a bumper cover",
  },
  'home.svc.bodywork': {
    src: bodyFillerBumperRepair900,
    srcSet: `${bodyFillerBumperRepair500} 500w, ${bodyFillerBumperRepair900} 900w`,
    width: 900,
    height: 497,
    sources: [{ w: 500, url: bodyFillerBumperRepair500 }, { w: 900, url: bodyFillerBumperRepair900 }],
    alt: "Sanded body filler repair on a front bumper corner beside the headlight during panel work at Sultan Motors",
  },
  'home.svc.collision': {
    src: collisionFramePull900,
    srcSet: `${collisionFramePull500} 500w, ${collisionFramePull900} 900w`,
    width: 900,
    height: 497,
    sources: [{ w: 500, url: collisionFramePull500 }, { w: 900, url: collisionFramePull900 }],
    alt: "Toyota RAV4 chained to a floor-anchored frame-pulling machine for structural collision repair at Sultan Motors",
  },
  'home.svc.diagnostics': {
    src: diagnosticsObdPortTile900,
    srcSet: `${diagnosticsObdPortTile500} 500w, ${diagnosticsObdPortTile900} 900w`,
    width: 900,
    height: 497,
    sources: [{ w: 500, url: diagnosticsObdPortTile500 }, { w: 900, url: diagnosticsObdPortTile900 }],
    alt: "Diagnostic scan tool connector plugged into a vehicle's OBD-II port during electronic fault testing",
  },
  'home.svc.maintenance': {
    src: maintenanceOilServiceTile900,
    srcSet: `${maintenanceOilServiceTile500} 500w, ${maintenanceOilServiceTile900} 900w`,
    width: 900,
    height: 497,
    sources: [{ w: 500, url: maintenanceOilServiceTile500 }, { w: 900, url: maintenanceOilServiceTile900 }],
    alt: "Fresh oil and a filter laid out beside a raised pickup truck before a scheduled oil service at Sultan Motors",
  },
  'home.svc.repairs': {
    src: heavyMechanicalEngineOut900,
    srcSet: `${heavyMechanicalEngineOut500} 500w, ${heavyMechanicalEngineOut900} 900w`,
    width: 900,
    height: 497,
    sources: [{ w: 500, url: heavyMechanicalEngineOut500 }, { w: 900, url: heavyMechanicalEngineOut900 }],
    alt: "Engine and front subframe removed onto a shop dolly beneath a vehicle raised on a hoist at Sultan Motors",
  },
  'home.visit': {
    src: shopExteriorBrampton2400,
    srcSet: `${shopExteriorBrampton1280} 1280w, ${shopExteriorBrampton2400} 2400w`,
    width: 2400,
    height: 976,
    sources: [{ w: 1280, url: shopExteriorBrampton1280 }, { w: 2400, url: shopExteriorBrampton2400 }],
    alt: "Exterior of the Sultan Motors auto repair and collision shop at 5 Melanie Dr Unit 2 in Brampton with the bay door open",
  },
  'home.why': {
    src: craftsmanshipPainterSpraying1280,
    srcSet: `${craftsmanshipPainterSpraying720} 720w, ${craftsmanshipPainterSpraying1280} 1280w`,
    width: 1280,
    height: 1362,
    sources: [{ w: 720, url: craftsmanshipPainterSpraying720 }, { w: 1280, url: craftsmanshipPainterSpraying1280 }],
    alt: "Sultan Motors refinishing technician in a full spray suit and respirator laying base coat inside the paint booth",
  },
  'svc.auto-body-repair-brampton.g1': {
    src: autobodyG1PanelPrep1000,
    srcSet: `${autobodyG1PanelPrep560} 560w, ${autobodyG1PanelPrep1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: autobodyG1PanelPrep560 }, { w: 1000, url: autobodyG1PanelPrep1000 }],
    alt: "Sedan on the hoist with the fender and hood sanded to primer and masked with tape for refinishing",
  },
  'svc.auto-body-repair-brampton.g2': {
    src: autobodyG2DoorSanded1000,
    srcSet: `${autobodyG2DoorSanded560} 560w, ${autobodyG2DoorSanded1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: autobodyG2DoorSanded560 }, { w: 1000, url: autobodyG2DoorSanded1000 }],
    alt: "Front door sanded down to primer and bare metal and outlined with masking tape during panel repair",
  },
  'svc.auto-body-repair-brampton.g3': {
    src: autobodyG3BlendPanel1000,
    srcSet: `${autobodyG3BlendPanel560} 560w, ${autobodyG3BlendPanel1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: autobodyG3BlendPanel560 }, { w: 1000, url: autobodyG3BlendPanel1000 }],
    alt: "SUV rear quarter panel half in original colour and half in primer, masked for a blended paint repair",
  },
  'svc.auto-body-repair-brampton.hero': {
    src: autobodyHeroPrimerCoupe2000,
    srcSet: `${autobodyHeroPrimerCoupe1100} 1100w, ${autobodyHeroPrimerCoupe2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: autobodyHeroPrimerCoupe1100 }, { w: 2000, url: autobodyHeroPrimerCoupe2000 }],
    alt: "Sports coupe in primer with the front bumper removed inside the Sultan Motors body shop in Brampton",
  },
  'svc.auto-body-repair-brampton.intro': {
    src: autobodyIntroPrimerDoor1400,
    srcSet: `${autobodyIntroPrimerDoor760} 760w, ${autobodyIntroPrimerDoor1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: autobodyIntroPrimerDoor760 }, { w: 1400, url: autobodyIntroPrimerDoor1400 }],
    alt: "Honda CR-V fitted with an unpainted replacement door panel next to the original paint before refinishing",
  },
  'svc.auto-body-repair-brampton.why': {
    src: autobodyWhyGuideCoat1400,
    srcSet: `${autobodyWhyGuideCoat760} 760w, ${autobodyWhyGuideCoat1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: autobodyWhyGuideCoat760 }, { w: 1400, url: autobodyWhyGuideCoat1400 }],
    alt: "Guide coat sanding across filler on an SUV rear quarter panel during body repair at Sultan Motors",
  },
  'svc.auto-electrical-repair-brampton.g1': {
    src: electricalG1Harness1000,
    srcSet: `${electricalG1Harness560} 560w, ${electricalG1Harness1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: electricalG1Harness560 }, { w: 1000, url: electricalG1Harness1000 }],
    alt: "Front-end wiring harness with connectors and battery leads exposed during auto electrical repair",
  },
  'svc.auto-electrical-repair-brampton.g2': {
    src: electricalG2WiringRepair1000,
    srcSet: `${electricalG2WiringRepair560} 560w, ${electricalG2WiringRepair1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: electricalG2WiringRepair560 }, { w: 1000, url: electricalG2WiringRepair1000 }],
    alt: "Technician in work gloves repairing exposed wiring inside a removed rear bumper assembly at Sultan Motors",
  },
  'svc.auto-electrical-repair-brampton.g3': {
    src: electricalG3BumperInternals560,
    srcSet: `${electricalG3BumperInternals560} 560w`,
    width: 560,
    height: 344,
    sources: [{ w: 560, url: electricalG3BumperInternals560 }],
    alt: "Technician working the inner structure and wiring of a detached rear bumper cover at Sultan Motors",
  },
  'svc.auto-electrical-repair-brampton.hero': {
    src: electricalHeroFrontClip2000,
    srcSet: `${electricalHeroFrontClip1100} 1100w, ${electricalHeroFrontClip2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: electricalHeroFrontClip1100 }, { w: 2000, url: electricalHeroFrontClip2000 }],
    alt: "Pickup truck with the front clip removed, exposing the radiator support and full wiring harness at Sultan Motors",
  },
  'svc.auto-electrical-repair-brampton.intro': {
    src: electricalIntroConnector1400,
    srcSet: `${electricalIntroConnector760} 760w, ${electricalIntroConnector1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: electricalIntroConnector760 }, { w: 1400, url: electricalIntroConnector1400 }],
    alt: "Ford pickup with the hood up and a wiring connector exposed below the bumper during electrical diagnosis",
  },
  'svc.auto-electrical-repair-brampton.why': {
    src: electricalWhyDashHarness1400,
    srcSet: `${electricalWhyDashHarness760} 760w, ${electricalWhyDashHarness1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: electricalWhyDashHarness760 }, { w: 1400, url: electricalWhyDashHarness1400 }],
    alt: "Cab-over flatbed truck with the dashboard and trim removed to access the wiring harness at Sultan Motors",
  },
  'svc.auto-repair-brampton.g1': {
    src: autoRepairG1RepairBay1000,
    srcSet: `${autoRepairG1RepairBay560} 560w, ${autoRepairG1RepairBay1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: autoRepairG1RepairBay560 }, { w: 1000, url: autoRepairG1RepairBay1000 }],
    alt: "Sultan Motors repair bay with a Dodge Challenger on the floor, hood raised, and a technician crossing the shop",
  },
  'svc.auto-repair-brampton.g2': {
    src: autoRepairG2Diagnostics1000,
    srcSet: `${autoRepairG2Diagnostics560} 560w, ${autoRepairG2Diagnostics1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: autoRepairG2Diagnostics560 }, { w: 1000, url: autoRepairG2Diagnostics1000 }],
    alt: "Technician reviewing live vehicle data on a handheld diagnostic scan tool during a repair",
  },
  'svc.auto-repair-brampton.g3': {
    src: autoRepairG3PowerTool1000,
    srcSet: `${autoRepairG3PowerTool560} 560w, ${autoRepairG3PowerTool1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: autoRepairG3PowerTool560 }, { w: 1000, url: autoRepairG3PowerTool1000 }],
    alt: "Technician using a cordless impact driver on exhaust hardware beneath a vehicle on the hoist at Sultan Motors",
  },
  'svc.auto-repair-brampton.hero': {
    src: autoRepairHeroShop2000,
    srcSet: `${autoRepairHeroShop1100} 1100w, ${autoRepairHeroShop2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: autoRepairHeroShop1100 }, { w: 2000, url: autoRepairHeroShop2000 }],
    alt: "Ford Super Duty pickup in the Sultan Motors service bay beside a two-post hoist in Brampton",
  },
  'svc.auto-repair-brampton.intro': {
    src: autoRepairIntroBay1400,
    srcSet: `${autoRepairIntroBay760} 760w, ${autoRepairIntroBay1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: autoRepairIntroBay760 }, { w: 1400, url: autoRepairIntroBay1400 }],
    alt: "Sultan Motors service bay with a Toyota RAV4 raised on a two-post hoist for repair work in Brampton",
  },
  'svc.auto-repair-brampton.why': {
    src: autoRepairWhyHeavyMechanical1400,
    srcSet: `${autoRepairWhyHeavyMechanical760} 760w, ${autoRepairWhyHeavyMechanical1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: autoRepairWhyHeavyMechanical760 }, { w: 1400, url: autoRepairWhyHeavyMechanical1400 }],
    alt: "Pickup truck on a two-post hoist with the bed removed, exposing frame rails, rear axle and driveshaft at Sultan Motors",
  },
  'svc.brake-repair-brampton.g1': {
    src: brakeG1FrontTeardown1000,
    srcSet: `${brakeG1FrontTeardown560} 560w, ${brakeG1FrontTeardown1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: brakeG1FrontTeardown560 }, { w: 1000, url: brakeG1FrontTeardown1000 }],
    alt: "Tesla Model Y front end stripped on the hoist with the wheel off and brake assembly accessible",
  },
  'svc.brake-repair-brampton.g2': {
    src: brakeG2CaliperInspection1000,
    srcSet: `${brakeG2CaliperInspection560} 560w, ${brakeG2CaliperInspection1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: brakeG2CaliperInspection560 }, { w: 1000, url: brakeG2CaliperInspection1000 }],
    alt: "Technician's gloved hand tracing a panel crease above a wheel fitted with a red brake caliper",
  },
  'svc.brake-repair-brampton.g3': {
    src: brakeG3RotorsPadsLift1000,
    srcSet: `${brakeG3RotorsPadsLift560} 560w, ${brakeG3RotorsPadsLift1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: brakeG3RotorsPadsLift560 }, { w: 1000, url: brakeG3RotorsPadsLift1000 }],
    alt: "Nissan Pathfinder raised on a two-post hoist for front and rear rotor and pad replacement",
  },
  'svc.brake-repair-brampton.hero': {
    src: brakeHeroWheelOffRotor2000,
    srcSet: `${brakeHeroWheelOffRotor1100} 1100w, ${brakeHeroWheelOffRotor2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: brakeHeroWheelOffRotor1100 }, { w: 2000, url: brakeHeroWheelOffRotor2000 }],
    alt: "Jaguar X-Type on a two-post hoist with the front wheel removed, exposing the brake rotor",
  },
  'svc.brake-repair-brampton.intro': {
    src: brakeIntroRotorHub1400,
    srcSet: `${brakeIntroRotorHub760} 760w, ${brakeIntroRotorHub1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: brakeIntroRotorHub760 }, { w: 1400, url: brakeIntroRotorHub1400 }],
    alt: "Brake rotor, hub and CV axle exposed in the wheel well with the wheel removed at Sultan Motors",
  },
  'svc.brake-repair-brampton.why': {
    src: brakeWhyRotorCaliper1400,
    srcSet: `${brakeWhyRotorCaliper760} 760w, ${brakeWhyRotorCaliper1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: brakeWhyRotorCaliper760 }, { w: 1400, url: brakeWhyRotorCaliper1400 }],
    alt: "Front brake rotor and red caliper exposed on a Tesla Model Y with the wheel removed",
  },
  'svc.car-diagnostics-brampton.g1': {
    src: diagnosticsG1ObdPort1000,
    srcSet: `${diagnosticsG1ObdPort560} 560w, ${diagnosticsG1ObdPort1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: diagnosticsG1ObdPort560 }, { w: 1000, url: diagnosticsG1ObdPort1000 }],
    alt: "Close view of a diagnostic scan tool connector seated in a vehicle's OBD-II diagnostic port",
  },
  'svc.car-diagnostics-brampton.g2': {
    src: diagnosticsG2FuseboxWiring1000,
    srcSet: `${diagnosticsG2FuseboxWiring560} 560w, ${diagnosticsG2FuseboxWiring1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: diagnosticsG2FuseboxWiring560 }, { w: 1000, url: diagnosticsG2FuseboxWiring1000 }],
    alt: "Relay and fuse box with wiring harness connectors exposed under the hood during electrical fault testing at Sultan Motors",
  },
  'svc.car-diagnostics-brampton.g3': {
    src: diagnosticsG3TechTeamBay560,
    srcSet: `${diagnosticsG3TechTeamBay560} 560w`,
    width: 560,
    height: 344,
    sources: [{ w: 560, url: diagnosticsG3TechTeamBay560 }],
    alt: "Sultan Motors technicians reviewing a job at the tool chest beside a vehicle with its hood raised in the Brampton bay",
  },
  'svc.car-diagnostics-brampton.hero': {
    src: diagnosticsHeroScanBay2000,
    srcSet: `${diagnosticsHeroScanBay1100} 1100w, ${diagnosticsHeroScanBay2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: diagnosticsHeroScanBay1100 }, { w: 2000, url: diagnosticsHeroScanBay2000 }],
    alt: "Technician running a diagnostic scan on a vehicle in the Sultan Motors service bay in Brampton",
  },
  'svc.car-diagnostics-brampton.intro': {
    src: diagnosticsIntroObdPlug1400,
    srcSet: `${diagnosticsIntroObdPlug760} 760w, ${diagnosticsIntroObdPlug1400} 1400w`,
    width: 1400,
    height: 1196,
    sources: [{ w: 760, url: diagnosticsIntroObdPlug760 }, { w: 1400, url: diagnosticsIntroObdPlug1400 }],
    alt: "Technician connecting a diagnostic scan tool to the OBD-II port beneath a vehicle's dashboard",
  },
  'svc.car-diagnostics-brampton.why': {
    src: diagnosticsWhyLiveData1400,
    srcSet: `${diagnosticsWhyLiveData760} 760w, ${diagnosticsWhyLiveData1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: diagnosticsWhyLiveData760 }, { w: 1400, url: diagnosticsWhyLiveData1400 }],
    alt: "Technician reading live engine data on a handheld diagnostic scan tool at an open engine bay",
  },
  'svc.car-maintenance-brampton.g1': {
    src: maintenanceG1SparkPlug1000,
    srcSet: `${maintenanceG1SparkPlug560} 560w, ${maintenanceG1SparkPlug1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: maintenanceG1SparkPlug560 }, { w: 1000, url: maintenanceG1SparkPlug1000 }],
    alt: "Worn spark plug removed from an engine during a tune up at Sultan Motors in Brampton",
  },
  'svc.car-maintenance-brampton.g2': {
    src: maintenanceG2OilBottles1000,
    srcSet: `${maintenanceG2OilBottles560} 560w, ${maintenanceG2OilBottles1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: maintenanceG2OilBottles560 }, { w: 1000, url: maintenanceG2OilBottles1000 }],
    alt: "Fresh engine oil ready beside a pickup truck during scheduled maintenance at Sultan Motors",
  },
  'svc.car-maintenance-brampton.g3': {
    src: maintenanceG3UnderbodyCheck560,
    srcSet: `${maintenanceG3UnderbodyCheck560} 560w`,
    width: 560,
    height: 344,
    sources: [{ w: 560, url: maintenanceG3UnderbodyCheck560 }],
    alt: "Technician working beneath a crossover raised on a two-post hoist at Sultan Motors",
  },
  'svc.car-maintenance-brampton.hero': {
    src: maintenanceHeroOilDrain2000,
    srcSet: `${maintenanceHeroOilDrain1100} 1100w, ${maintenanceHeroOilDrain2000} 2000w`,
    width: 2000,
    height: 981,
    sources: [{ w: 1100, url: maintenanceHeroOilDrain1100 }, { w: 2000, url: maintenanceHeroOilDrain2000 }],
    alt: "Ford Super Duty dually raised on a two-post hoist for scheduled maintenance at Sultan Motors in Brampton",
  },
  'svc.car-maintenance-brampton.intro': {
    src: maintenanceIntroOilJugs1400,
    srcSet: `${maintenanceIntroOilJugs760} 760w, ${maintenanceIntroOilJugs1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: maintenanceIntroOilJugs760 }, { w: 1400, url: maintenanceIntroOilJugs1400 }],
    alt: "Pickup truck on the hoist with the hood open and fresh engine oil ready for an oil change at Sultan Motors",
  },
  'svc.car-maintenance-brampton.why': {
    src: maintenanceWhyOilService1400,
    srcSet: `${maintenanceWhyOilService760} 760w, ${maintenanceWhyOilService1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: maintenanceWhyOilService760 }, { w: 1400, url: maintenanceWhyOilService1400 }],
    alt: "BMW X1 on the hoist at Sultan Motors during an oil change, cooling system flush and transmission fluid service",
  },
  'svc.car-painting-brampton.g1': {
    src: paintG1MaskedRear1000,
    srcSet: `${paintG1MaskedRear560} 560w, ${paintG1MaskedRear1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: paintG1MaskedRear560 }, { w: 1000, url: paintG1MaskedRear1000 }],
    alt: "Masked rear end of a hatchback prepared for refinishing inside the Sultan Motors paint booth",
  },
  'svc.car-painting-brampton.g2': {
    src: paintG2MaskingDetail1000,
    srcSet: `${paintG2MaskingDetail560} 560w, ${paintG2MaskingDetail1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: paintG2MaskingDetail560 }, { w: 1000, url: paintG2MaskingDetail1000 }],
    alt: "Rear quarter panel taped along the body lines with primer patches ready for a blended colour match",
  },
  'svc.car-painting-brampton.g3': {
    src: paintG3FinishedGloss1000,
    srcSet: `${paintG3FinishedGloss560} 560w, ${paintG3FinishedGloss1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: paintG3FinishedGloss560 }, { w: 1000, url: paintG3FinishedGloss1000 }],
    alt: "Honda CR-V with a glossy finished repaint inside the Sultan Motors paint booth in Brampton",
  },
  'svc.car-painting-brampton.hero': {
    src: paintHeroBoothSpray2000,
    srcSet: `${paintHeroBoothSpray1100} 1100w, ${paintHeroBoothSpray2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: paintHeroBoothSpray1100 }, { w: 2000, url: paintHeroBoothSpray2000 }],
    alt: "Sultan Motors refinishing technician spraying a sedan inside the downdraft paint booth in Brampton",
  },
  'svc.car-painting-brampton.intro': {
    src: paintIntroSpraying1400,
    srcSet: `${paintIntroSpraying760} 760w, ${paintIntroSpraying1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: paintIntroSpraying760 }, { w: 1400, url: paintIntroSpraying1400 }],
    alt: "Technician in full protective equipment applying base coat to a masked vehicle in the Sultan Motors paint booth",
  },
  'svc.car-painting-brampton.why': {
    src: paintWhyMaskedBooth1400,
    srcSet: `${paintWhyMaskedBooth760} 760w, ${paintWhyMaskedBooth1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: paintWhyMaskedBooth760 }, { w: 1400, url: paintWhyMaskedBooth1400 }],
    alt: "Coupe fully masked in plastic and tape, centred in the evenly lit Sultan Motors spray booth before painting",
  },
  'svc.collision-repair-brampton.g1': {
    src: collisionG1FrontDamage1000,
    srcSet: `${collisionG1FrontDamage560} 560w, ${collisionG1FrontDamage1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: collisionG1FrontDamage560 }, { w: 1000, url: collisionG1FrontDamage1000 }],
    alt: "Shattered headlight and destroyed bumper corner on a collision-damaged Toyota RAV4 at Sultan Motors",
  },
  'svc.collision-repair-brampton.g2': {
    src: collisionG2Sectioning1000,
    srcSet: `${collisionG2Sectioning560} 560w, ${collisionG2Sectioning1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: collisionG2Sectioning560 }, { w: 1000, url: collisionG2Sectioning1000 }],
    alt: "Vehicle sectioned into structural components across the Sultan Motors collision floor during a major repair",
  },
  'svc.collision-repair-brampton.g3': {
    src: collisionG3Restored1000,
    srcSet: `${collisionG3Restored560} 560w, ${collisionG3Restored1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: collisionG3Restored560 }, { w: 1000, url: collisionG3Restored1000 }],
    alt: "Mercedes-Benz GLE with a colour-matched replacement bumper installed and finished after collision repair",
  },
  'svc.collision-repair-brampton.hero': {
    src: collisionHeroFrameAnchor2000,
    srcSet: `${collisionHeroFrameAnchor1100} 1100w, ${collisionHeroFrameAnchor2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: collisionHeroFrameAnchor1100 }, { w: 2000, url: collisionHeroFrameAnchor2000 }],
    alt: "Toyota RAV4 anchored to a frame-pulling machine for structural collision repair at Sultan Motors in Brampton",
  },
  'svc.collision-repair-brampton.intro': {
    src: collisionIntroTeardown1400,
    srcSet: `${collisionIntroTeardown760} 760w, ${collisionIntroTeardown1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: collisionIntroTeardown760 }, { w: 1400, url: collisionIntroTeardown1400 }],
    alt: "Collision-damaged Toyota RAV4 with the hood open and bumper removed beside pulling equipment at Sultan Motors",
  },
  'svc.collision-repair-brampton.why': {
    src: collisionWhyStructural1400,
    srcSet: `${collisionWhyStructural760} 760w, ${collisionWhyStructural1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: collisionWhyStructural760 }, { w: 1400, url: collisionWhyStructural1400 }],
    alt: "Structural splice in progress with a replacement front clip joined to the rear body section on the hoist",
  },
  'svc.engine-repair-brampton.g1': {
    src: engineG1RadiatorCondenser1000,
    srcSet: `${engineG1RadiatorCondenser560} 560w, ${engineG1RadiatorCondenser1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: engineG1RadiatorCondenser560 }, { w: 1000, url: engineG1RadiatorCondenser1000 }],
    alt: "Front fascia removed to expose the radiator, air conditioning condenser and cooling stack during engine work",
  },
  'svc.engine-repair-brampton.g2': {
    src: engineG2FrontClipApart1000,
    srcSet: `${engineG2FrontClipApart560} 560w, ${engineG2FrontClipApart1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: engineG2FrontClipApart560 }, { w: 1000, url: engineG2FrontClipApart1000 }],
    alt: "Front clip fully disassembled with the engine bay open during a major mechanical repair at Sultan Motors",
  },
  'svc.engine-repair-brampton.g3': {
    src: engineG3BayHoodUp1000,
    srcSet: `${engineG3BayHoodUp560} 560w, ${engineG3BayHoodUp1000} 1000w`,
    width: 1000,
    height: 613,
    sources: [{ w: 560, url: engineG3BayHoodUp560 }, { w: 1000, url: engineG3BayHoodUp1000 }],
    alt: "Sports coupe in a Sultan Motors bay with the hood raised for engine inspection",
  },
  'svc.engine-repair-brampton.hero': {
    src: engineHeroHoodUpLift2000,
    srcSet: `${engineHeroHoodUpLift1100} 1100w, ${engineHeroHoodUpLift2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: engineHeroHoodUpLift1100 }, { w: 2000, url: engineHeroHoodUpLift2000 }],
    alt: "Jaguar sedan raised on a hoist with the hood open and engine bay exposed at Sultan Motors in Brampton",
  },
  'svc.engine-repair-brampton.intro': {
    src: engineIntroBayOpen1400,
    srcSet: `${engineIntroBayOpen760} 760w, ${engineIntroBayOpen1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: engineIntroBayOpen760 }, { w: 1400, url: engineIntroBayOpen1400 }],
    alt: "Engine bay opened up for mechanical repair inside the Sultan Motors workshop in Brampton",
  },
  'svc.engine-repair-brampton.why': {
    src: engineWhyRemovedEngine1400,
    srcSet: `${engineWhyRemovedEngine760} 760w, ${engineWhyRemovedEngine1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: engineWhyRemovedEngine760 }, { w: 1400, url: engineWhyRemovedEngine1400 }],
    alt: "Complete engine and front subframe removed onto a shop dolly during an engine repair at Sultan Motors",
  },
  'svc.safety-standards-certificate-brampton.hero': {
    src: safetyHeroVehicleOnHoist2000,
    srcSet: `${safetyHeroVehicleOnHoist1100} 1100w, ${safetyHeroVehicleOnHoist2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: safetyHeroVehicleOnHoist1100 }, { w: 2000, url: safetyHeroVehicleOnHoist2000 }],
    alt: "Vehicle raised on a two-post hoist for a safety inspection at Sultan Motors in Brampton",
  },
  'svc.safety-standards-certificate-brampton.intro': {
    src: safetyIntroJettaInspection1400,
    srcSet: `${safetyIntroJettaInspection760} 760w, ${safetyIntroJettaInspection1400} 1400w`,
    width: 1400,
    height: 1196,
    sources: [{ w: 760, url: safetyIntroJettaInspection760 }, { w: 1400, url: safetyIntroJettaInspection1400 }],
    alt: "Volkswagen Jetta raised on a hoist at Sultan Motors for an Ontario safety standards inspection",
  },
  'svc.safety-standards-certificate-brampton.why': {
    src: safetyWhyInspectionLift1400,
    srcSet: `${safetyWhyInspectionLift760} 760w, ${safetyWhyInspectionLift1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: safetyWhyInspectionLift760 }, { w: 1400, url: safetyWhyInspectionLift1400 }],
    alt: "BMW on the hoist at Sultan Motors during a safety inspection and front rotor and pad service",
  },
  'svc.suspension-repair-brampton.g1': {
    src: suspensionG1CoilMacro1000,
    srcSet: `${suspensionG1CoilMacro560} 560w, ${suspensionG1CoilMacro1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: suspensionG1CoilMacro560 }, { w: 1000, url: suspensionG1CoilMacro1000 }],
    alt: "Macro view of a front strut and coil spring assembly inside the wheel well at Sultan Motors",
  },
  'svc.suspension-repair-brampton.g2': {
    src: suspensionG2StrutDetail1000,
    srcSet: `${suspensionG2StrutDetail560} 560w, ${suspensionG2StrutDetail1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: suspensionG2StrutDetail560 }, { w: 1000, url: suspensionG2StrutDetail1000 }],
    alt: "Front strut and coil spring assembly photographed in the wheel arch during suspension service",
  },
  'svc.suspension-repair-brampton.g3': {
    src: suspensionG3Underbody560,
    srcSet: `${suspensionG3Underbody560} 560w`,
    width: 560,
    height: 343,
    sources: [{ w: 560, url: suspensionG3Underbody560 }],
    alt: "Vehicle underside on a two-post hoist showing subframe and suspension components",
  },
  'svc.suspension-repair-brampton.hero': {
    src: suspensionHeroStrutArm2000,
    srcSet: `${suspensionHeroStrutArm1100} 1100w, ${suspensionHeroStrutArm2000} 2000w`,
    width: 2000,
    height: 981,
    sources: [{ w: 1100, url: suspensionHeroStrutArm1100 }, { w: 2000, url: suspensionHeroStrutArm2000 }],
    alt: "Front strut, control arm and orange brake caliper exposed with the wheel removed during suspension work",
  },
  'svc.suspension-repair-brampton.intro': {
    src: suspensionIntroHoistCorner1400,
    srcSet: `${suspensionIntroHoistCorner760} 760w, ${suspensionIntroHoistCorner1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: suspensionIntroHoistCorner760 }, { w: 1400, url: suspensionIntroHoistCorner1400 }],
    alt: "Honda Del Sol on a two-post hoist with the front corner stripped for suspension repair",
  },
  'svc.suspension-repair-brampton.why': {
    src: suspensionWhyStrutCoil1400,
    srcSet: `${suspensionWhyStrutCoil760} 760w, ${suspensionWhyStrutCoil1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: suspensionWhyStrutCoil760 }, { w: 1400, url: suspensionWhyStrutCoil1400 }],
    alt: "Front suspension strut and coil spring above a clean brake rotor and orange caliper inside the wheel arch",
  },
  'svc.transmission-repair-brampton.g1': {
    src: transmissionG1Underbody560,
    srcSet: `${transmissionG1Underbody560} 560w`,
    width: 560,
    height: 343,
    sources: [{ w: 560, url: transmissionG1Underbody560 }],
    alt: "Vehicle underside on a two-post hoist showing the subframe, driveline and control arms",
  },
  'svc.transmission-repair-brampton.g2': {
    src: transmissionG2SubframeDriveline1000,
    srcSet: `${transmissionG2SubframeDriveline560} 560w, ${transmissionG2SubframeDriveline1000} 1000w`,
    width: 1000,
    height: 614,
    sources: [{ w: 560, url: transmissionG2SubframeDriveline560 }, { w: 1000, url: transmissionG2SubframeDriveline1000 }],
    alt: "Close underbody view showing the driveline, subframe and exhaust beneath a lifted vehicle",
  },
  'svc.transmission-repair-brampton.g3': {
    src: transmissionG3UnderbodyTech560,
    srcSet: `${transmissionG3UnderbodyTech560} 560w`,
    width: 560,
    height: 344,
    sources: [{ w: 560, url: transmissionG3UnderbodyTech560 }],
    alt: "Technician working beneath a crossover raised on a two-post hoist near the driveline",
  },
  'svc.transmission-repair-brampton.hero': {
    src: transmissionHeroFrameDriveline2000,
    srcSet: `${transmissionHeroFrameDriveline1100} 1100w, ${transmissionHeroFrameDriveline2000} 2000w`,
    width: 2000,
    height: 980,
    sources: [{ w: 1100, url: transmissionHeroFrameDriveline1100 }, { w: 2000, url: transmissionHeroFrameDriveline2000 }],
    alt: "Pickup truck on the hoist with the bed removed, exposing the frame, driveline and rear axle at Sultan Motors",
  },
  'svc.transmission-repair-brampton.intro': {
    src: transmissionIntroUnitJack1400,
    srcSet: `${transmissionIntroUnitJack760} 760w, ${transmissionIntroUnitJack1400} 1400w`,
    width: 1400,
    height: 1197,
    sources: [{ w: 760, url: transmissionIntroUnitJack760 }, { w: 1400, url: transmissionIntroUnitJack1400 }],
    alt: "Technician supporting an automatic transmission on a transmission jack beneath a vehicle on the hoist",
  },
  'svc.transmission-repair-brampton.why': {
    src: transmissionWhyDriveline1400,
    srcSet: `${transmissionWhyDriveline760} 760w, ${transmissionWhyDriveline1400} 1400w`,
    width: 1400,
    height: 1284,
    sources: [{ w: 760, url: transmissionWhyDriveline760 }, { w: 1400, url: transmissionWhyDriveline1400 }],
    alt: "Pickup truck on the hoist with the bed removed, exposing the driveshaft, rear axle and frame rails",
  },
}

/** Returns the photo for a slot, or undefined when no authentic image exists yet. */
export function photo(slot: string): Photo | undefined {
  return photos[slot]
}
