/**
 * Single source of truth for the business identity, the production origin, and
 * every URL the site emits. Canonicals, Open Graph tags, JSON-LD, the sitemap,
 * and the prerenderer all read from here, so the deploy domain is a one-line
 * change rather than a find-and-replace across a dozen files.
 */

/**
 * Production origin, no trailing slash.
 *
 * Resolved at build time by `resolveSiteUrl` in vite.config.ts, which prefers
 * an explicit VITE_SITE_URL, falls back to the Vercel project's production
 * domain, then to the checked-in default. Everything canonical-related derives
 * from this, so it must match the domain the site is actually served from.
 */
export const SITE_URL = (
  import.meta.env?.VITE_SITE_URL ?? 'https://www.sultanmotors.ca'
).replace(/\/+$/, '')

/**
 * True on preview and branch deployments, where the same content is served
 * from a second URL. Every page then ships `noindex`, so a preview never
 * competes with production in the index.
 */
export const SITE_NOINDEX: boolean = import.meta.env?.VITE_NOINDEX === true

export const SITE_NAME = 'Sultan Motors'
export const SITE_LOCALE = 'en_CA'
export const SITE_LANG = 'en-CA'

export const business = {
  name: 'Sultan Motors',
  legalName: 'Sultan Motors',
  /** Digits-only form for tel: links. */
  phoneRaw: '+19057991331',
  /** E.164 form for schema.org. */
  phoneSchema: '+1-905-799-1331',
  /** Human-readable form for on-page copy. */
  phoneDisplay: '(905) 799-1331',
  streetAddress: '5 Melanie Dr Unit 2',
  addressLocality: 'Brampton',
  addressRegion: 'ON',
  postalCode: 'L6T 4K8',
  addressCountry: 'CA',
  /**
   * Approximate shop coordinates. Verify against the Google Business Profile
   * listing before launch — Google cross-checks these against the GBP pin.
   */
  latitude: 43.7113,
  longitude: -79.6866,
  /** Generic price tier. Adjust if the shop publishes a rate card. */
  priceRange: '$$',
  foundingYear: '2004',
  areaServed: [
    'Brampton',
    'Mississauga',
    'Caledon',
    'Vaughan',
    'Etobicoke',
    'Toronto',
  ],
} as const

/**
 * Verified public profiles only. Empty strings are filtered out of `sameAs`
 * and hide the matching icon in the header and footer, so an unconfigured
 * profile never ships as a dead link or a wrong schema reference.
 */
export const socialProfiles = {
  googleBusiness: '',
  instagram: '',
  facebook: '',
} as const

/** Non-empty social URLs, for schema.org `sameAs`. */
export const sameAs = Object.values(socialProfiles).filter(Boolean)

export const openingHours = [
  {
    days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'] as string[],
    opens: '08:00',
    closes: '18:00',
    label: 'Mon to Fri',
    display: '8am to 6pm',
  },
  {
    days: ['Saturday'] as string[],
    opens: '09:00',
    closes: '15:00',
    label: 'Saturday',
    display: '9am to 3pm',
  },
]

/** Absolute URL for a site path. `absoluteUrl('/')` returns the bare origin. */
export function absoluteUrl(path: string): string {
  if (/^https?:\/\//.test(path)) return path
  const clean = path.startsWith('/') ? path : `/${path}`
  return clean === '/' ? `${SITE_URL}/` : `${SITE_URL}${clean.replace(/\/+$/, '')}`
}

/** Stable schema.org node ids, so every page references one shared entity. */
export const schemaId = {
  business: `${SITE_URL}/#business`,
  website: `${SITE_URL}/#website`,
  organization: `${SITE_URL}/#organization`,
  page: (path: string) => `${absoluteUrl(path)}#webpage`,
  breadcrumb: (path: string) => `${absoluteUrl(path)}#breadcrumb`,
}

/** Social share image. Generated by scripts/optimize_images.py into public/. */
export const OG_IMAGE = {
  path: '/og-image.jpg',
  width: 1200,
  height: 630,
  alt: 'Sultan Motors auto repair and collision shop in Brampton, Ontario',
} as const

export const ogImageUrl = absoluteUrl(OG_IMAGE.path)

/**
 * Square brand mark for the schema.org `logo` property, which Google may use
 * in the knowledge panel. It must be square and at least 112x112 — the 1200x630
 * social card is the wrong shape for this slot.
 *
 * This is currently the generated "SM" monogram. Replace public/icon-512.png
 * with the shop's real logo when one is available.
 */
export const logoUrl = absoluteUrl('/icon-512.png')

export const postalAddressSchema = {
  '@type': 'PostalAddress',
  streetAddress: business.streetAddress,
  addressLocality: business.addressLocality,
  addressRegion: business.addressRegion,
  postalCode: business.postalCode,
  addressCountry: business.addressCountry,
} as const

export const openingHoursSchema = openingHours.map((block) => ({
  '@type': 'OpeningHoursSpecification',
  dayOfWeek: block.days,
  opens: block.opens,
  closes: block.closes,
}))

/**
 * The shared AutoRepair entity. Every page links to this by `@id` instead of
 * repeating a partial copy, so search engines resolve one business, not
 * fifteen near-duplicates.
 */
export const businessSchema = {
  '@type': ['AutoRepair', 'AutoBodyShop', 'LocalBusiness'],
  '@id': schemaId.business,
  name: business.name,
  description:
    'Sultan Motors is a full service auto repair and collision shop in Brampton, Ontario, offering diagnostics, engine and transmission repair, brakes, suspension, maintenance, bodywork, painting, and Ontario safety standards inspections.',
  url: `${SITE_URL}/`,
  telephone: business.phoneSchema,
  image: ogImageUrl,
  logo: logoUrl,
  priceRange: business.priceRange,
  foundingDate: business.foundingYear,
  address: postalAddressSchema,
  geo: {
    '@type': 'GeoCoordinates',
    latitude: business.latitude,
    longitude: business.longitude,
  },
  openingHoursSpecification: openingHoursSchema,
  areaServed: business.areaServed.map((name) => ({ '@type': 'City', name })),
  ...(sameAs.length ? { sameAs } : {}),
} as const

export const websiteSchema = {
  '@type': 'WebSite',
  '@id': schemaId.website,
  url: `${SITE_URL}/`,
  name: SITE_NAME,
  inLanguage: SITE_LANG,
  publisher: { '@id': schemaId.business },
} as const
